In [64]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statistics as stats

In [97]:
#28.Which reason of visit has maximum mortality rate.

#To create dataframe for to datasheet
edvisitsdf=pd.read_excel("HospitalDataBase .xlsx", sheet_name="EDVisits")
dischargesdf=pd.read_excel("HospitalDataBase .xlsx", sheet_name="Discharges")

#To merge 2 data set with common column 

combinedf = edvisitsdf[["PatientID","ReasonForVisit"]].merge(dischargesdf[["PatientID","DischargeDisposition"]],
                                                   on = "PatientID",
                                                   how = "inner")
#df_mor=combinedf.query('DischargeDisposition=="Expired"')

#df_rv=combinedf.groupby("ReasonForVisit")


df_morrate = combinedf.groupby("ReasonForVisit")["DischargeDisposition"].apply(lambda x: (x=='Expired').sum()).nlargest(1).reset_index(name='Patientcount')

print(df_morrate)
#df_morrate = combinedf.groupby("ReasonForVisit")["DischargeDisposition"].apply(lambda x: (x=='Expired').sum()).reset_index(name='Patientcount').max()

  ReasonForVisit  Patientcount
0          Fever            25

In [80]:
#29.Calculate average LOS.

# To use, Mean we have to import statistics module

import statistics as stats

# To create dataframe of readmissionregistry

readmissiondf=pd.read_excel("HospitalDataBase .xlsx", sheet_name="ReAdmissionRegistry")

#def Average(readmissiondf.ExpectedLOS) :
#  return sum(readmissiondf.ExpectedLOS) / len(readmissiondf.ExpectedLOS)

#To calculate average,omport statistics module.
aver=stats.mean(readmissiondf.ExpectedLOS)
      
# Printing average of the LOS
print("Average LOS =", round(aver,2))

Average LOS = 8.82

In [245]:
#30.Which patient id has most entries in readmission registry.

#To read the Data Frame
readmissiondf=pd.read_excel("HospitalDataBase .xlsx", sheet_name="ReAdmissionRegistry")

# code for getting patient has Most entries

mostp_id=readmissiondf['PatientID'].mode()

#mostp_id=readmissiondf['PatientID'].value_counts().idxmax()----One more option

# To print result
mostp_id

0    23
Name: PatientID, dtype: int64

In [118]:
#46.Write a code to split a sentence into words using regex.

#To import regex
import string, re

# Create a String of Sentence
s = "Hello Friends ,This is my First Python Hackathon"

# Code for split a sentence into words
re.sub(fr'([{string.punctuation}])\B', r' \1', s).split()

['Hello', 'Friends', ',This', 'is', 'my', 'First', 'Python', 'Hackathon']

In [220]:
#47.Using indexing , loc to retrieve the row with maximum BloodPressureSystolic.

ambul_df=pd.read_excel("HospitalDataBase .xlsx", sheet_name="AmbulatoryVisits")


# retrieving maximum BPS rows by loc method
rows=ambul_df.loc[(ambul_df.BloodPressureSystolic == max(ambul_df.BloodPressureSystolic))]  

#To display the row with maximum BloodPressureSystolic 
rows

,VisitID,PatientMRN,ProviderID,DateofVisit,DateScheduled,VisitDepartmentID,VisitType,BloodPressureSystolic,BloodPressureDiastolic,Pulse,VisitStatus
236,933,884,27,2019-02-14,2019-01-22 19:26:49.163,12,Telemedicine,190.0,143.989174,74.976879,Completed
251,888,906,24,2019-03-31,2019-03-17 23:21:17.361,10,New,190.0,137.207999,52.666922,Completed
424,314,63,7,2019-04-05,2019-03-24 22:31:26.092,11,Telemedicine,190.0,121.539859,95.471260,Completed
432,740,892,31,2019-03-14,2019-03-11 15:08:33.963,8,Physical,190.0,145.343479,94.849021,Completed
677,929,880,23,2019-02-10,2019-01-22 13:32:14.549,8,Follow Up,190.0,144.313400,82.781940,Completed
869,839,857,12,2019-03-17,2019-02-23 09:05:43.676,8,Follow Up,190.0,130.997386,71.829542,Completed
934,482,866,14,2019-05-04,2019-04-13 07:54:49.580,5,New,190.0,124.736359,69.731779,Canceled

In [221]:
#49.Retrieve the rows where SBP<140 and DBP<80.

#To create DataFrame
ambul_df=pd.read_excel("HospitalDataBase .xlsx", sheet_name="AmbulatoryVisits")

#To retrieve the rows where SBP<140 and DBP<80. 
newdf=ambul_df.loc[(ambul_df.BloodPressureSystolic <140) & (ambul_df.BloodPressureDiastolic <80)]

#To display the rows
newdf

,VisitID,PatientMRN,ProviderID,DateofVisit,DateScheduled,VisitDepartmentID,VisitType,BloodPressureSystolic,BloodPressureDiastolic,Pulse,VisitStatus
5,809,894,31,2019-03-13,2019-02-28 10:28:01.091,2,Physical,121.0,57.692485,60.402573,No Show
16,707,859,36,2019-03-16,2019-02-26 17:42:39.779,6,Follow Up,137.0,72.756586,64.071361,No Show
18,503,887,12,2019-01-21,2019-01-07 06:04:17.575,7,Follow Up,131.0,74.163851,97.248671,No Show
19,710,862,1,2019-03-19,2019-03-03 11:39:03.145,9,Telemedicine,127.0,66.406797,94.537837,No Show
23,711,863,1,2019-03-20,2019-03-10 07:34:56.766,10,Telemedicine,124.0,77.303553,77.926874,No Show
...,...,...,...,...,...,...,...,...,...,...,...
909,177,815,32,2019-02-22,2019-02-04 06:53:41.987,9,Follow Up,122.0,67.615828,52.742629,Canceled
929,786,871,34,2019-03-25,2019-02-26 09:48:42.832,3,Telemedicine,122.0,78.210501,53.760978,Canceled
932,394,623,6,2019-02-05,2019-01-10 05:43:34.544,9,Physical,130.0,75.114100,80.951071,Canceled
941,399,638,11,2019-02-10,2019-02-02 20:49:56.868,2,Physical,121.0,64.896818,68.496869,Canceled
943,403,650,15,2019-02-14,2019-02-11 00:47:42.216,6,Physical,129.0,68.506636,62.732434,Canceled

In [244]:
#50.Which departmentID has maximum number of visits scheduled.

#To read the Data Frame
ambuldf=pd.read_excel("HospitalDataBase .xlsx", sheet_name="AmbulatoryVisits")

# code for getting patient has Maximum visits

max_visit=ambuldf['VisitDepartmentID'].mode()
#max_visit=ambuldf['VisitDepartmentID'].value_counts().idxmax()----One more option

# To print result
max_visit

0    11
Name: VisitDepartmentID, dtype: int64